version: '3'
services:

  db:
    container_name: db
    image: mongo:latest
    ports:
      - "27018:27017"

  db-seed:
    build: ./db-seed
    links:
      - "db:mymongo"
    depends_on:
      - "db"

  web:
    build: ./web
    container_name: web
    restart: always
    ports:
      - "3000:3000"
    links:
      - "db:mymongo"
    depends_on:
      - "db-seed"
    command: bash -c "cd /usr/src/app && bundle exec rake db:mongoid:create_indexes RAILS_ENV=development && rails s"